beer_search_v1:
  path: /api/v1/beers
  controller: \App\Controller\Beers\BeerSearcherController
  methods: GET

beer_find_by_id_v1:
  path: /api/v1/beers/{id}
  controller: \App\Controller\Beers\BeerFindByIdController
  methods: GET
